name: Check and Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check latest version
      run: |
        if [ "$(curl https://api.github.com/repos/mingzhixian/Easycontrol/releases/latest -s | jq -r .name)" != "$(curl https://api.github.com/repos/xishang0128/Easycontrol-build/releases/latest -s | jq -r .name)" ]; then
          echo "tag=$(curl https://api.github.com/repos/mingzhixian/Easycontrol/releases/latest -s | jq -r .name)" >> $GITHUB_ENV
          echo "is_old=1" >> $GITHUB_ENV
        fi

    - name: Checkout target repository
      if: ${{ env.is_old == '1' }}
      uses: actions/checkout@v4
      with:
        repository: mingzhixian/Easycontrol

    - name: modify
      if: ${{ env.is_old == '1' }}
      run: |
        sed -i 's/import top.saymzx.easycontrol.app.helper.ActiveHelper;//g' easycontrol/app/src/main/java/top/saymzx/easycontrol/app/ActiveActivity.java
        sed -i 's/ActiveHelper.active(activeKey)/true/g' easycontrol/app/src/main/java/top/saymzx/easycontrol/app/ActiveActivity.java
        sed -i 's/ActiveHelper.deactivate(AppData.setting.getActiveKey())/true/g' easycontrol/app/src/main/java/top/saymzx/easycontrol/app/ActiveActivity.java

    - name: Setup Java
      if: ${{ env.is_old == '1' }}
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Android SDK
      if: ${{ env.is_old == '1' }}
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      if: ${{ env.is_old == '1' }}
      run: chmod +x easycontrol/gradlew

    - name: Build
      if: ${{ env.is_old == '1' }}
      working-directory: easycontrol
      run: |
        ./gradlew copyrelease
        ./gradlew assembleRelease

    - name: Upload Release
      if: ${{ env.is_old == '1' && success() }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.tag }}
        files: easycontrol/app/build/outputs/apk/release/*.apk
